# multistage build 

# build environment
FROM node:alpine as build
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY . ./
ENV PATH /usr/src/app/node_modules/.bin:$PATH
COPY package.json /usr/src/app/package.json
RUN yarn install --silent
RUN yarn global add @vue/cli@3.7.0
RUN yarn build

# production environment
FROM nginx:1.16.0-alpine
COPY --from=build /usr/src/app/dist /usr/share/nginx/html
# with Vue Router, it needs to change the default Nginx config at build time:
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/conf.d
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

# docker build -f Dockerfile-prod -t swoy-vue-web-client:prod .
# docker run -it -p 80:80 --rm swoy-vue-web-client:prod